-- CREATE DATABASE medassist2

CREATE TABLE Users(id VARCHAR(255), name VARCHAR(255) NOT NULL, phone_number VARCHAR(20) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT user, createdAt VARCHAR(255) NOT NULL )