POST http://localhost:5203/orgs/create-new
Content-Type: application/json

{
    "name": "Chuka University",
    "description": "A Chuka University dispensary",
    "profile_image": "image3"
}

### Update an organization
PUT http://localhost:5203/orgs/update/348811eb-1139-48e6-874b-beebac822236
Content-Type: application/json

{
    "name": "Meru University",
    "description": "A Meru University hospital",
    "profile_image":"image2"
}

### Get all organization
GET http://localhost:5203/orgs/all
Content-Type: application/json

### Get one organization
GET http://localhost:5203/orgs/3e49c51a-c175-4524-abcc-7bc3ee924d1a
Content-Type: application/json


### delete an organization
DELETE http://localhost:5203/orgs/delete/3e49c51a-c175-4524-abcc-7bc3ee924d1a
Content-Type: application/json