POST http://localhost:5203/users/create 
Content-Type: application/json

{
    "name": "Alvin Doe",
    "email": "alvin@yopmail.com",
    "phone_number":"0701345621",
    "password": "12345678"
}

### GET ALL USERS
GET http://localhost:5203/users/all-users 
Content-Type: application/json

### LOGIN
POST http://localhost:5203/auth/login 
Content-Type: application/json

{
    "email": "alvin@yopmail.com",
    "password": "12345678"
}
