### LOGIN
POST http://localhost:5203/auth/login 
Content-Type: application/json

{
    "email": "sammymuthuurikinyua@gmail.com",
    "password": "Pass@123"
}


### Check token details
GET http://localhost:5203/auth/check-details 
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwOGVlM2I0LTcxNjEtNGIzOC04Njg3LTM5MjViZTllZTI2NiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkB5b3BtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE3NTc0MTg5LCJleHAiOjE3MTc1ODEzODl9.n8UejN2VlCYa1pA_iRcfiJlh6FgHcxRdGKig9qnC8T0


