POST http://localhost:5203/orgs/create-new
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3YmQ3MDBmLTU0NTMtNGQ2MS05YjQ1LTQwOGNlMjI0OGJlMSIsIm5hbWUiOiJQZXRlciBEb2UiLCJlbWFpbCI6Im1idXJ1a2lnYW55YUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MTgwMTA2MTMsImV4cCI6MTcxODAxNzgxM30.SSaDblxejoDOsghu-LcvNam1jKwMLf8FbHvtmZhLSds

{
    "name": "Eldoret University",
    "description": "A Eldoret University dispensary",
    "profile_image": "image4"
}

### Update an organization
PUT http://localhost:5203/orgs/update/348811eb-1139-48e6-874b-beebac822236
Content-Type: application/json

{
    "name": "Meru University",
    "description": "A Meru University hospital",
    "profile_image":"image2"
}

### Get all organization
GET http://localhost:5203/orgs/all
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0NDhkMDUxLTliMGEtNGI4NS04MDIyLTYzMWQ5YmE4NjE3OCIsIm5hbWUiOiJTYW1teSBEb2UiLCJlbWFpbCI6InNhbW15bXV0aHV1cmlraW55dWFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwiaWF0IjoxNzE4MDEwMTM0LCJleHAiOjE3MTgwMTczMzR9.H-ZEp0HFiJXZGdmJn_kd62a5CQ2ecg23ZSxh6NXIiV4

### Get one organization
GET http://localhost:5203/orgs/33133039-ef28-4edf-8965-4625a5e37eb8
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhMTI4NTkwLThlODgtNDFiZS04ZmUzLTJhZmUxMWQ4MmFjZiIsIm5hbWUiOiJBbHZpbiBEb2UiLCJlbWFpbCI6ImFsdmluQHlvcG1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTc1NzMwMTMsImV4cCI6MTcxNzU4MDIxM30.rZtaIT7nCsNbsU8wRdE8OJ1K-3GxqJxef1bGOp5AdCU

### delete an organization
DELETE http://localhost:5203/orgs/delete/4fbca5a3-e567-4987-9352-bcb5e18f1af7
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJhMTI4NTkwLThlODgtNDFiZS04ZmUzLTJhZmUxMWQ4MmFjZiIsIm5hbWUiOiJBbHZpbiBEb2UiLCJlbWFpbCI6ImFsdmluQHlvcG1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTc1NzMwMTMsImV4cCI6MTcxNzU4MDIxM30.rZtaIT7nCsNbsU8wRdE8OJ1K-3GxqJxef1bGOp5AdCU