POST http://localhost:5203/users/create 
Content-Type: application/json

{
    "name": "Eric Doe",
    "email": "ericmurigi04@gmail.com",
    "phone_number":"0734319111",
    "password": "Pass@123"
}

### GET ALL USERS
GET http://localhost:5203/users/all-users 
Content-Type: application/json

### LOGIN
POST http://localhost:5203/auth/login 
Content-Type: application/json

{
    "email": "alvin@yopmail.com",
    "password": "12345678"
}
