version: '3.8'
services:
  t2gdb:
    container_name: t2gtalksdb
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: t2gtalks
    ports:
      - '5436:5432'
    volumes:
      - t2gtalksdata:/var/lib/postgres

  t2gpgadmin:
    container_name: pgadmin_t2gtalks
    image: dpage/pgadmin4
    depends_on:
      - t2gdb
    ports:
      - '5052:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  
  t2giveserver:
    container_name: t2gtalksserver
    depends_on:
      - t2gpgadmin
    build: ./
    restart: unless-stopped
    ports:
      - '4115:4115'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  t2gtalksdata: