POST http://localhost:4115/product/create
Content-Type: application/json

{
    "name": "Mobile Phhone",
    "description": "Samsung",
    "quantity": 100
}

### Update product
PUT http://localhost:4115/product/update/49399295-48e3-449b-ad78-cb45cb3959dc
Content-Type: application/json

{
    "name": "Phone",
    "quantity": 100
}


### VIEW ALL PRODUCTS
GET http://localhost:4115/product/all
Content-Type: application/json


### VIEW ALL PRODUCTS
GET http://localhost:4115/product/single/49399295-48e3-449b-ad78-cb45cb3959dc
Content-Type: application/json


### DELETE PRODUCTS
DELETE http://localhost:4115/product/delete/15107e39-50a9-4048-9f16-1607b8c0ffd9
Content-Type: application/json