POST http://localhost:4116/post/create
Content-Type: application/json

{
    "content": "Learning Testing With Jasmine on Angular",
    "images": [
        "https://cdn.pixabay.com/photo/2016/11/12/23/34/learn-1820039_640.jpg", 
        "https://cdn.pixabay.com/photo/2014/04/03/10/11/boy-310099_640.png",
        "https://cdn.pixabay.com/photo/2022/02/26/01/23/study-7035108_640.png"
    ],
    "authorId": "17236d6e-930b-4f4b-a9f2-54fafeb8ca1b"
}

### EDIT POST
PUT http://localhost:4116/post/update/3b582715-e98f-449d-a335-519874e56f53
Content-Type: application/json

{
    "content": "Happy to announce that, I got a new role as a Software Developer",
    "images": [
        "https://cdn.pixabay.com/photo/2021/08/04/13/06/software-developer-6521720_640.jpg", 
        "https://cdn.pixabay.com/photo/2021/08/05/12/36/software-development-6523979_640.jpg"
    ]
}


### GET USERS POSTS
GET http://localhost:4116/post/all

### GET SINGLE POST
GET http://localhost:4116/post/single/3b582715-e98f-449d-a335-519874e56f53


### GET USERS POSTS
GET http://localhost:4116/post/all/a5e7eef1-9acc-4d2e-a39b-b1fecf0d291d
Content-Type: application/json


### DELETE POST
DELETE http://localhost:4116/post/delete
Content-Type: application/json

{
    "post_id":"f57f0699-a4a2-407a-903b-e7d1ffae8b31",
    "user_id":"17236d6e-930b-4f4b-a9f2-54fafeb8ca1b"
}