# POST http://localhost:4115/user/create
POST https://ca-t2gtalksapi-rveojdckddxac.agreeableground-d1650c91.eastus2.azurecontainerapps.io/user/create
Content-Type: application/json

{
    "username":"John Doe",
    "email":"johndoe@yopmail.com",
    "password":"Pass@123",
    "name":"John Doe",
    "bio": "",
    "location":"",
    "d_o_b": "",
    "website": "",
    "profileImage": "",
    "headerImage":""
}

### Update user
PUT https://ca-t2gtalksapi-rveojdckddxac.agreeableground-d1650c91.eastus2.azurecontainerapps.io/user/update/7136bba5-17bb-444c-8d6f-ec3a577b5961
Content-Type: application/json

{
    "username":"johndoe",
    "email":"johndoe@yopmail.com",
    "password":"12345678",
    "name":"John Doe",
    "bio": "",
    "location":"",
    "d_o_b": "",
    "website": "",
    "profileImage": "",
    "headerImage":""
}


### VIEW ALL USERS
GET https://ca-t2gtalksapi-rveojdckddxac.agreeableground-d1650c91.eastus2.azurecontainerapps.io/user/all
Content-Type: application/json


### VIEW One user
GET https://ca-t2gtalksapi-rveojdckddxac.agreeableground-d1650c91.eastus2.azurecontainerapps.io/user/single/a5e7eef1-9acc-4d2e-a39b-b1fecf0d291d
Content-Type: application/json


### DELETE user
DELETE https://ca-t2gtalksapi-rveojdckddxac.agreeableground-d1650c91.eastus2.azurecontainerapps.io/user/delete/d4695adb-e24e-40fc-84f3-2bdde872b843
Content-Type: application/json